import { useState } from "react";
import { ClipboardList, LoaderCircle, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { formatDate } from "@/lib/buildforge";

const CLIENT_TOOLS = [
  { id: "dashboard", label: "Visão geral" },
  { id: "projects", label: "Projetos" },
  { id: "builds", label: "Builds" },
  { id: "artifacts", label: "Artefatos" },
  { id: "releases", label: "Releases" },
  { id: "support", label: "Suporte" },
] as const;

export default function AdminPage() {
  const { user } = useAuth();
  const users = trpc.buildforge.admin.users.useQuery(undefined, { enabled: user?.role === "admin" });
  const audit = trpc.buildforge.admin.audit.useQuery(undefined, { enabled: user?.role === "admin" });
  const utils = trpc.useUtils();
  const update = trpc.buildforge.admin.updateUser.useMutation({ onSuccess: () => { toast.success("Acesso atualizado."); void utils.buildforge.admin.users.invalidate(); void utils.buildforge.admin.audit.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createClient = trpc.buildforge.admin.createClient.useMutation({ onSuccess: (created) => { toast.success(`Cliente ${created?.email ?? "criado"} cadastrado.`); void utils.buildforge.admin.users.invalidate(); setForm({ name: "", email: "", password: "", buildLimit: "3", allowedTools: ["dashboard", "projects", "builds", "artifacts", "releases"] }); }, onError: (error) => toast.error(error.message) });
  const [limits, setLimits] = useState<Record<number, string>>({});
  const [form, setForm] = useState({ name: "", email: "", password: "", buildLimit: "3", allowedTools: ["dashboard", "projects", "builds", "artifacts", "releases"] as string[] });

  const toggleTool = (id: string) => setForm((previous) => ({ ...previous, allowedTools: previous.allowedTools.includes(id) ? previous.allowedTools.filter((tool) => tool !== id) : [...previous.allowedTools, id] }));
  if (user?.role !== "admin") return <div className="mx-auto max-w-3xl rounded-3xl border border-amber-200 bg-amber-50 p-8 text-amber-900 dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-200"><ShieldCheck className="h-7 w-7" /><h1 className="mt-4 text-xl font-semibold">Área administrativa</h1><p className="mt-2 text-sm">A criação de clientes e a gestão de limites permanecem disponíveis somente para administradores.</p></div>;

  return <div className="mx-auto max-w-7xl space-y-6 pb-8"><header><h1 className="text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Administração</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Crie clientes, defina credenciais iniciais, escolha ferramentas e controle a quantidade de builds.</p></header>
    <section className="rounded-2xl border border-indigo-200 bg-indigo-50/50 p-5 shadow-sm dark:border-indigo-950 dark:bg-indigo-950/20"><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-indigo-500" /><h2 className="font-semibold text-slate-950 dark:text-white">Cadastrar cliente</h2></div><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); createClient.mutate({ name: form.name, email: form.email, password: form.password, buildLimit: Number(form.buildLimit), allowedTools: form.allowedTools as Array<(typeof CLIENT_TOOLS)[number]["id"]> }); }}><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nome do cliente" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" /><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="E-mail do cliente" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" /><input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Senha inicial (mín. 8 caracteres)" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" /><input required type="number" min={-1} value={form.buildLimit} onChange={(event) => setForm({ ...form, buildLimit: event.target.value })} placeholder="Limite de builds (-1 ilimitado)" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" /><div className="md:col-span-2"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Ferramentas liberadas</p><div className="flex flex-wrap gap-2">{CLIENT_TOOLS.map((tool) => <label key={tool.id} className="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><input checked={form.allowedTools.includes(tool.id)} onChange={() => toggleTool(tool.id)} type="checkbox" />{tool.label}</label>)}</div></div><button disabled={createClient.isPending || !form.allowedTools.length} className="w-fit rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{createClient.isPending ? "Criando..." : "Criar cliente e senha"}</button></form></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4 dark:border-slate-800"><UsersRound className="h-4 w-4 text-indigo-500" /><h2 className="font-semibold text-slate-950 dark:text-white">Pessoas usuárias</h2></div>{users.isLoading ? <div className="grid min-h-48 place-items-center"><LoaderCircle className="h-5 w-5 animate-spin text-indigo-500" /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:bg-slate-900"><tr><th className="px-5 py-3">Pessoa</th><th className="px-5 py-3">Papel</th><th className="px-5 py-3">Limite</th><th className="px-5 py-3">Uso</th><th className="px-5 py-3">Ação</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{users.data?.map((entry) => <tr key={entry.id}><td className="px-5 py-4"><p className="font-semibold text-slate-900 dark:text-white">{entry.name ?? "Sem nome"}</p><p className="mt-0.5 text-xs text-slate-500">{entry.email ?? "Sem e-mail"}</p></td><td className="px-5 py-4"><select value={entry.role === "user" ? "member" : entry.role} onChange={(event) => update.mutate({ userId: entry.id, role: event.target.value as "admin" | "member", buildLimit: Number(limits[entry.id] ?? entry.buildLimit) })} className="rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900"><option value="member">Cliente</option><option value="admin">Admin</option></select></td><td className="px-5 py-4"><input value={limits[entry.id] ?? entry.buildLimit} onChange={(event) => setLimits((old) => ({ ...old, [entry.id]: event.target.value }))} type="number" min={-1} className="w-20 rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-900" /></td><td className="px-5 py-4 text-slate-600 dark:text-slate-300">{entry.buildsUsed}</td><td className="px-5 py-4"><button onClick={() => update.mutate({ userId: entry.id, role: entry.role === "admin" ? "admin" : "member", buildLimit: Number(limits[entry.id] ?? entry.buildLimit) })} className="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white dark:bg-indigo-600">Salvar</button></td></tr>)}</tbody></table></div>}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4 dark:border-slate-800"><ClipboardList className="h-4 w-4 text-indigo-500" /><h2 className="font-semibold text-slate-950 dark:text-white">Auditoria recente</h2></div>{audit.isLoading ? <div className="grid min-h-44 place-items-center"><LoaderCircle className="h-5 w-5 animate-spin text-indigo-500" /></div> : audit.data?.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{audit.data.map((event) => <div key={event.id} className="flex items-start gap-4 px-5 py-4"><span className="mt-1.5 h-2 w-2 rounded-full bg-indigo-500" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900 dark:text-white">{event.action}</p><p className="mt-1 text-xs text-slate-500">{event.entityType} {event.entityId ? `#${event.entityId}` : ""} · {event.actorName ?? event.actorEmail ?? "Sistema"} · {formatDate(event.createdAt)}</p></div></div>)}</div> : <div className="px-6 py-14 text-center text-sm text-slate-500">Ainda não há eventos auditáveis.</div>}</section></div>;
}
