import { BellRing, CheckCircle2, CircleAlert, Clock3, LoaderCircle, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { formatDate } from "@/lib/buildforge";

const eventLabel: Record<string, string> = { build_queued: "Build entrou na fila", build_succeeded: "Build concluído", build_failed: "Build falhou" };

export default function NotificationsPage() {
  const notifications = trpc.buildforge.notifications.list.useQuery(undefined, { refetchInterval: 15_000 });
  if (notifications.isError) return <div className="mx-auto max-w-5xl space-y-6 pb-8"><header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-500">Operação</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Notificações</h1></header><section className="grid min-h-64 place-items-center rounded-2xl border border-rose-200 bg-rose-50 p-6 text-center dark:border-rose-900/60 dark:bg-rose-950/20"><div><CircleAlert className="mx-auto h-9 w-9 text-rose-600" /><h2 className="mt-4 font-semibold text-rose-950 dark:text-rose-100">Não foi possível carregar as notificações</h2><p className="mt-1 text-sm text-rose-800/80 dark:text-rose-200/75">Verifique a conexão e tente novamente.</p><button onClick={() => void notifications.refetch()} className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl bg-rose-600 px-4 text-sm font-semibold text-white hover:bg-rose-500"><RefreshCw className="h-4 w-4" /> Tentar novamente</button></div></section></div>;
  return <div className="mx-auto max-w-5xl space-y-6 pb-8"><header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-500">Operação</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Notificações</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Eventos reais da fila e o resultado das entregas para acompanhar a operação sem consultar logs manualmente.</p></header><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">{notifications.isLoading ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-indigo-500" /></div> : notifications.data?.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{notifications.data.map((item) => { const failed = item.event === "build_failed"; const queued = item.event === "build_queued"; const Icon = failed ? CircleAlert : queued ? Clock3 : CheckCircle2; return <article key={item.id} className="flex gap-4 px-5 py-4"><span className={`mt-0.5 rounded-xl p-2 ${failed ? "bg-rose-500/10 text-rose-600" : queued ? "bg-amber-500/10 text-amber-600" : "bg-emerald-500/10 text-emerald-600"}`}><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-slate-950 dark:text-white">{eventLabel[item.event] ?? item.event}</h2><span className="text-xs text-slate-500">{formatDate(item.createdAt)}</span></div><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{item.projectName} · Build #{item.buildId}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-500">{item.summary}</p><span className="mt-3 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">Entrega: {item.status}</span></div></article>; })}</div> : <div className="grid min-h-64 place-items-center px-6 text-center"><div><BellRing className="mx-auto h-10 w-10 text-slate-300 dark:text-slate-700" /><h2 className="mt-4 font-semibold text-slate-900 dark:text-white">Nenhum evento registrado</h2><p className="mt-1 text-sm text-slate-500">Os avisos de fila, sucesso e falha aparecerão aqui quando houver builds.</p></div></div>}</section></div>;
}
