import { Activity, CheckCircle2, ClipboardList, Cpu, FolderKanban } from "lucide-react";
import { trpc } from "@/lib/trpc";

function ReportMetric({ label, value, detail, icon: Icon }: { label: string; value: number; detail: string; icon: typeof Activity }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><Icon className="h-5 w-5 text-violet-500" /><p className="mt-4 text-3xl font-semibold text-slate-950 dark:text-white">{value}</p><p className="mt-1 text-sm font-medium text-slate-700 dark:text-slate-300">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>;
}

export default function ReportsPage() {
  const summary = trpc.buildforge.dashboard.summary.useQuery();
  if (summary.isLoading) return <div className="grid min-h-[40vh] place-items-center text-sm text-slate-500">Carregando relatório operacional…</div>;
  if (summary.error || !summary.data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200">Não foi possível montar o relatório.</div>;
  const { projects, builds, workers, recentBuilds } = summary.data;
  const completedRate = builds.total ? Math.round((builds.succeeded / builds.total) * 100) : 0;
  const failed = recentBuilds.filter((build) => build.status === "failed").length;
  return <div className="mx-auto max-w-7xl space-y-6 pb-8"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-500">Dados operacionais</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Relatórios</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Indicadores reais da operação atual. Clientes visualizam apenas os dados aos quais têm acesso.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReportMetric label="Projetos ativos" value={projects.active} detail={`${projects.total} no total`} icon={FolderKanban} /><ReportMetric label="Taxa de conclusão" value={completedRate} detail={`${builds.succeeded} builds concluídas`} icon={CheckCircle2} /><ReportMetric label="Builds em fila" value={builds.queued + builds.running} detail={`${builds.running} em execução`} icon={Activity} /><ReportMetric label="Workers online" value={workers.online} detail={`${workers.total} cadastrados`} icon={Cpu} /></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-500/10 p-2 text-violet-600 dark:text-violet-300"><ClipboardList className="h-5 w-5" /></span><div><h2 className="font-semibold text-slate-950 dark:text-white">Leitura rápida</h2><p className="text-xs text-slate-500">Baseada nas últimas {recentBuilds.length} builds disponíveis.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-4 text-emerald-900 dark:bg-emerald-500/10 dark:text-emerald-100"><p className="text-xs font-bold uppercase tracking-wide">Concluídas</p><p className="mt-2 text-2xl font-semibold">{builds.succeeded}</p></div><div className="rounded-xl bg-amber-50 p-4 text-amber-900 dark:bg-amber-500/10 dark:text-amber-100"><p className="text-xs font-bold uppercase tracking-wide">Em operação</p><p className="mt-2 text-2xl font-semibold">{builds.queued + builds.running}</p></div><div className="rounded-xl bg-rose-50 p-4 text-rose-900 dark:bg-rose-500/10 dark:text-rose-100"><p className="text-xs font-bold uppercase tracking-wide">Falhas recentes</p><p className="mt-2 text-2xl font-semibold">{failed}</p></div></div></section></div>;
}
