import { Boxes, LoaderCircle, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { frameworkLabel } from "@/lib/buildforge";

export default function TemplatesPage() {
  const templates = trpc.buildforge.templates.list.useQuery();
  const utils = trpc.useUtils();
  const create = trpc.buildforge.templates.createProject.useMutation({ onSuccess: () => { toast.success("Projeto criado a partir do template."); void utils.buildforge.projects.list.invalidate(); void utils.buildforge.dashboard.summary.invalidate(); }, onError: (error) => toast.error(error.message) });
  return <div className="mx-auto max-w-7xl space-y-6 pb-8"><header><h1 className="text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Templates</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Comece com uma estrutura pronta e personalize antes de gerar o primeiro build.</p></header>{templates.isLoading ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-indigo-500" /></div> : templates.data?.length ? <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.data.map((template) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950" key={template.id}><span className="inline-flex rounded-xl bg-violet-500/10 p-2 text-violet-600 dark:text-violet-300"><Boxes className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-300">{template.category}</p><h2 className="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{template.name}</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{template.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 dark:border-slate-800"><span className="text-xs font-semibold text-slate-500">{frameworkLabel(template.framework)}</span><button onClick={() => create.mutate({ templateId: template.id })} disabled={create.isPending} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white dark:bg-indigo-600">Usar template</button></div></article>)}</section> : <section className="rounded-3xl border border-dashed border-slate-300 bg-white py-20 text-center dark:border-slate-800 dark:bg-slate-950"><Sparkles className="mx-auto h-10 w-10 text-violet-400" /><h2 className="mt-4 font-semibold text-slate-900 dark:text-white">Catálogo em preparação</h2><p className="mt-1 text-sm text-slate-500">Os templates de loja, catálogo, IPTV, delivery, agenda e WebView aparecem aqui.</p></section>}</div>;
}
