type StudioPreviewFile = { filePath: string; content: string; language: string };
type StudioPreview = { project: { name: string; projectType: string; framework: string }; files: StudioPreviewFile[] };

function escapeHtml(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
}

function isCheckersProject(preview: StudioPreview) {
  return /\b(damas|checkers)\b/i.test(`${preview.project.name} ${preview.project.framework} ${preview.files.map((file) => file.content.slice(0, 300)).join(" ")}`);
}

type CheckersTheme = { label: string; title: string; start: string; end: string; opponentLabel: string; opponentTitle: string; opponentStart: string; opponentEnd: string; boardLight: string; boardDark: string; medieval: boolean; competitive: boolean };

function detectCheckersTheme(preview: StudioPreview): CheckersTheme {
  const configFile = preview.files.find((file) => file.filePath === "studio-preview.json")?.content;
  let configuredColor = "";
  let configuredTheme = "";
  let configuredOpponentColor = "";
  let configuredBoard = "";
  let configuredMode = "";
  try { const config = JSON.parse(configFile ?? "{}") as { checkers?: { pieceColor?: string; opponentColor?: string; board?: string; theme?: string; mode?: string } }; configuredColor = String(config.checkers?.pieceColor ?? "").toLowerCase(); configuredOpponentColor = String(config.checkers?.opponentColor ?? "").toLowerCase(); configuredBoard = String(config.checkers?.board ?? "").toLowerCase(); configuredTheme = String(config.checkers?.theme ?? "").toLowerCase(); configuredMode = String(config.checkers?.mode ?? "").toLowerCase(); } catch { configuredColor = ""; }
  const source = preview.files.map((file) => file.content).join("\n").toLowerCase();
  const medieval = configuredTheme === "medieval" || /medieval|reino|castelo/.test(source);
  const competitive = configuredMode === "competitive" || /ranqueamento|\belo\b|matchmaking|torneio|espectador|replay/.test(source);
  const palette = (color: string, fallback: [string, string, string, string]) => color === "pink" ? ["rosas", "Rosas", "#f9a8d4", "#be185d"] : color === "yellow" ? ["amarelas", "Amarelas", "#fde047", "#ca8a04"] : color === "red" ? ["vermelhas", "Vermelhas", "#fb7185", "#b91c1c"] : color === "green" ? ["verdes", "Verdes", "#4ade80", "#15803d"] : color === "blue" ? ["azuis", "Azuis", "#38bdf8", "#1d4ed8"] : fallback;
  const board = configuredBoard === "marble" ? ["#e5e7eb", "#374151"] : configuredBoard === "wood" ? ["#d6a56a", "#5b2e14"] : configuredBoard === "obsidian" ? ["#71717a", "#18181b"] : medieval ? ["#d8bb80", "#623617"] : ["#e7d7be", "#7c4b35"];
  const theme = (color: string, fallback: [string, string, string, string]): CheckersTheme => { const [label, title, start, end] = palette(color, fallback); const [opponentLabel, opponentTitle, opponentStart, opponentEnd] = palette(configuredOpponentColor, ["roxas", "Roxas", "#c084fc", "#6d28d9"]); return { label, title, start, end, opponentLabel, opponentTitle, opponentStart, opponentEnd, boardLight: board[0], boardDark: board[1], medieval, competitive }; };
  if (configuredColor) return theme(configuredColor, ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
  if (/rosa|pink|#f9a8d4|#be185d/.test(source)) return theme("pink", ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
  if (/amarel|#ffd60a|#facc15|#eab308/.test(source)) return theme("yellow", ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
  if (/vermelh|#ef4444|#dc2626|#f43f5e/.test(source)) return theme("red", ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
  if (/verde|#22c55e|#16a34a/.test(source)) return theme("green", ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
  return theme("blue", ["azuis", "Azuis", "#38bdf8", "#1d4ed8"]);
}

export function createCheckersPreviewDocument(name: string, theme: CheckersTheme = { label: "azuis", title: "Azuis", start: "#38bdf8", end: "#1d4ed8", opponentLabel: "roxas", opponentTitle: "Roxas", opponentStart: "#c084fc", opponentEnd: "#6d28d9", boardLight: "#e7d7be", boardDark: "#7c4b35", medieval: false, competitive: false }) {
  const safeName = escapeHtml(name);
  const medievalPresentation = theme.medieval ? `<style>
body{background:radial-gradient(circle at 12% 4%,#9a5a21 0,#3a1d0b 32%,#130905 76%)!important}.game{position:relative}.game:before{content:"";position:absolute;inset:9px 7px auto;height:5px;border-radius:999px;background:linear-gradient(90deg,transparent,#f9d878,#8d4a16,#f9d878,transparent);opacity:.92}.eyebrow{color:#f7cf73!important;text-shadow:0 1px 0 #2a1207}.medieval-banner{margin:10px 0 3px;color:#f5dca3;font-family:Georgia,serif;font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}.board-wrap{position:relative;border:6px ridge #c38a36!important;background:linear-gradient(145deg,#5a2d11,#1f0d05)!important;box-shadow:0 0 0 3px #241006,0 18px 45px rgba(0,0,0,.5)!important}.board-wrap:before,.board-wrap:after{content:"♜";position:absolute;z-index:2;color:#f2cb73;font-family:Georgia,serif;font-size:22px;line-height:1;text-shadow:0 2px 0 #3e1d08}.board-wrap:before{left:8px;top:6px}.board-wrap:after{right:8px;bottom:6px;transform:rotate(180deg)}.board{border:10px ridge #d29a47!important;box-shadow:inset 0 0 0 3px #4a210c,0 0 0 2px #251005!important}.cell.light{background:linear-gradient(135deg,#ecd49d,#c69b52)!important}.cell.dark{background:linear-gradient(135deg,#7c3f16,#3f1b0b)!important}.piece{inset:11%!important;border:3px solid rgba(255,239,192,.78)!important;box-shadow:inset 0 5px 8px rgba(255,255,255,.26),inset 0 -7px 10px rgba(0,0,0,.38),0 4px 8px rgba(0,0,0,.55)!important}.piece:after{position:absolute;inset:0;display:grid;place-items:center;font-family:Georgia,serif;font-size:clamp(15px,3vw,27px);font-weight:700;text-shadow:0 2px 2px rgba(0,0,0,.58)}.piece.blue:after{content:"♜";color:#fff1bd}.piece.violet:after{content:"♛";color:#fce7ff}.piece.king:before{content:"✦"!important;font-size:clamp(9px,2vw,15px)!important;z-index:2;color:#ffd770!important}.card{background:linear-gradient(155deg,rgba(56,25,10,.92),rgba(18,8,4,.92))!important;border-color:rgba(245,197,103,.32)!important}.card h2{color:#f5dca3}.reset{background:linear-gradient(135deg,#a6691f,#5d2810)!important;border:1px solid #e4b85c!important}.status{border-color:rgba(245,203,108,.5)!important;background:rgba(104,55,18,.5)!important;color:#fff0c0!important}
	</style>` : "";
  const competitivePresentation = theme.competitive ? `<style>.arena-nav{display:flex;gap:7px;overflow:auto;margin:0 0 14px;padding-bottom:3px}.arena-tab{border:1px solid rgba(255,255,255,.13);border-radius:999px;background:#121a32;color:#cbd5e1;padding:8px 11px;font-size:11px;font-weight:800;white-space:nowrap;cursor:pointer}.arena-tab.active{background:linear-gradient(135deg,#ec4899,#7c3aed);color:#fff;border-color:transparent}.arena-panel{margin-top:18px;border:1px solid rgba(192,132,252,.3);border-radius:18px;background:linear-gradient(135deg,rgba(76,29,149,.28),rgba(15,23,42,.88));padding:15px}.arena-panel h2{margin:0;color:#fff;font-size:16px}.arena-panel p{margin:6px 0 0;color:#cbd5e1;font-size:12px;line-height:1.5}.arena-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.arena-stat{border-radius:12px;background:rgba(15,23,42,.76);padding:10px;color:#94a3b8;font-size:10px}.arena-stat strong{display:block;margin-top:3px;color:#fff;font-size:16px}.arena-cta{margin-top:12px;border:0;border-radius:11px;padding:10px 12px;background:#ec4899;color:#fff;font-weight:800;cursor:pointer}@media(max-width:400px){.arena-grid{grid-template-columns:1fr 1fr}.arena-stat:last-child{grid-column:span 2}}</style>` : "";
  const competitiveMarkup = theme.competitive ? `<nav class="arena-nav" aria-label="Modos competitivos"><button class="arena-tab active" data-arena="play">Partida</button><button class="arena-tab" data-arena="rank">Ranking ELO</button><button class="arena-tab" data-arena="cup">Torneios</button><button class="arena-tab" data-arena="watch">Espectador</button></nav><section id="arena-panel" class="arena-panel"><h2>Fila competitiva</h2><p>Best-of 3 · 3 min por lado · matchmaking rápido</p><div class="arena-grid"><div class="arena-stat">ELO<strong>1.284</strong></div><div class="arena-stat">Sequência<strong>4 vitórias</strong></div><div class="arena-stat">Temporada<strong>Prata II</strong></div></div><button class="arena-cta" id="arena-action">Entrar na fila</button></section>` : "";
  const competitiveScript = theme.competitive ? `<script>const arena={play:['Fila competitiva','Best-of 3 · 3 min por lado · matchmaking rápido','Entrar na fila'],rank:['Ranking ELO','Você está em #128 na divisão Prata II. Vitória contra jogadores mais fortes rende mais pontos.','Ver classificação'],cup:['Copa dos Reinos','Chave automática de 16 jogadores · próxima rodada em 18 min.','Entrar no torneio'],watch:['Arena ao vivo','Assista partidas públicas, pause, reveja jogadas e converse no chat moderado.','Assistir agora']};document.querySelectorAll('[data-arena]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-arena]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=arena[b.dataset.arena],p=document.getElementById('arena-panel');p.querySelector('h2').textContent=d[0];p.querySelector('p').textContent=d[1];p.querySelector('button').textContent=d[2]})</script>` : "";
  const document = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeName}</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 15% 0,#352466,#090d1c 52%,#050814);color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.game{width:min(960px,100%);margin:0 auto;padding:28px 18px 44px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:22px}.eyebrow{margin:0 0 5px;color:#c4b5fd;font-size:11px;font-weight:800;letter-spacing:.16em}.top h1{margin:0;font-size:clamp(24px,4vw,38px);letter-spacing:-.04em}.status{border:1px solid rgba(167,139,250,.35);border-radius:999px;background:rgba(124,58,237,.16);padding:9px 13px;font-size:12px;font-weight:700;color:#ede9fe}.layout{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:22px}.board-wrap{border:1px solid rgba(255,255,255,.12);border-radius:26px;background:rgba(15,23,42,.72);padding:16px;box-shadow:0 24px 60px rgba(0,0,0,.3)}.board{aspect-ratio:1;display:grid;grid-template-columns:repeat(8,1fr);overflow:hidden;border-radius:14px;border:6px solid #291c38;box-shadow:0 0 0 1px rgba(255,255,255,.15)}.cell{position:relative;border:0;padding:0;cursor:pointer}.cell.light{background:#e7d7be}.cell.dark{background:#7c4b35}.cell.selected{outline:4px solid #fbbf24;outline-offset:-4px;z-index:1}.cell.move:after{content:"";position:absolute;inset:37%;border-radius:50%;background:rgba(254,240,138,.9)}.piece{position:absolute;inset:14%;border-radius:50%;border:3px solid rgba(255,255,255,.55);box-shadow:inset 0 5px 8px rgba(255,255,255,.18),inset 0 -7px 10px rgba(0,0,0,.25),0 4px 7px rgba(0,0,0,.35)}.piece.blue{background:linear-gradient(145deg,#38bdf8,#1d4ed8)}.piece.violet{background:linear-gradient(145deg,#c084fc,#6d28d9)}.piece.king:before{content:"♛";position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:clamp(14px,3vw,25px);text-shadow:0 1px 2px #111}.side{display:flex;flex-direction:column;gap:12px}.card{border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:16px;background:rgba(15,23,42,.74)}.card h2{margin:0 0 8px;font-size:15px}.card p{margin:0;color:#cbd5e1;font-size:13px;line-height:1.55}.score{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:13px}.score div{border-radius:12px;padding:10px;background:#111a31;font-size:11px;color:#94a3b8}.score strong{display:block;color:white;font-size:22px;margin-top:3px}.reset{border:0;border-radius:12px;padding:12px;background:#7c3aed;color:white;font-weight:800;cursor:pointer}.reset:hover{background:#8b5cf6}.note{margin:15px 2px 0;color:#94a3b8;font-size:12px;line-height:1.55}@media(max-width:720px){.game{padding:18px 12px 32px}.layout{grid-template-columns:1fr}.side{display:grid;grid-template-columns:1fr 1fr}.side .card:last-of-type{grid-column:span 2}.top{align-items:flex-start}.status{white-space:nowrap}}@media(max-width:400px){.side{grid-template-columns:1fr}.side .card:last-of-type{grid-column:auto}}
</style></head><body><main class="game"><header class="top"><div><p class="eyebrow">BUILD FORGE STUDIO · JOGO INTERATIVO</p><h1>${safeName}</h1></div><span id="turn" class="status">Vez das peças azuis</span></header><section class="layout"><div><div class="board-wrap"><div id="board" class="board" aria-label="Tabuleiro de damas"></div></div><p class="note">Clique em uma peça e depois em uma casa marcada. Capturas por salto também estão habilitadas nesta prévia.</p></div><aside class="side"><section class="card"><h2>Partida local</h2><p>Prévia funcional criada pelo Studio. Você pode pedir pelo chat novos modos, placar, torneios, cronômetro ou um adversário com IA.</p><div class="score"><div>Azuis<strong id="blue-score">12</strong></div><div>Roxas<strong id="violet-score">12</strong></div></div></section><section class="card"><h2>Como jogar</h2><p>As azuis começam e avançam para baixo. As roxas avançam para cima. Chegue à última linha para virar dama.</p></section><button id="reset" class="reset">Reiniciar partida</button></aside></section></main><script>
const board=document.getElementById('board'),turnNode=document.getElementById('turn'),blueScore=document.getElementById('blue-score'),violetScore=document.getElementById('violet-score');let turn='blue',selected=null;const fresh=()=>Array.from({length:8},(_,r)=>Array.from({length:8},(_,c)=>((r+c)%2? (r<3?{player:'blue',king:false}:r>4?{player:'violet',king:false}:null):null)));let state=fresh();const dirs=p=>p.king?[[-1,-1],[-1,1],[1,-1],[1,1]]:p.player==='blue'?[[1,-1],[1,1]]:[[-1,-1],[-1,1]];const inBoard=(r,c)=>r>=0&&r<8&&c>=0&&c<8;function moves(r,c){const p=state[r][c];if(!p)return[];return dirs(p).flatMap(([dr,dc])=>{const one=[r+dr,c+dc],jump=[r+2*dr,c+2*dc];const out=[];if(inBoard(...one)&&!state[one[0]][one[1]])out.push({to:one,capture:null});if(inBoard(...jump)&&state[one[0]][one[1]]?.player!==p.player&&!state[jump[0]][jump[1]])out.push({to:jump,capture:one});return out})}function render(){board.innerHTML='';let b=0,v=0;state.flat().forEach(p=>{if(p?.player==='blue')b++;if(p?.player==='violet')v++});blueScore.textContent=b;violetScore.textContent=v;turnNode.textContent='Vez das peças '+(turn==='blue'?'azuis':'roxas');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.className='cell '+((r+c)%2?'dark':'light');cell.dataset.r=r;cell.dataset.c=c;if(selected&&selected[0]===r&&selected[1]===c)cell.classList.add('selected');if(selected&&moves(...selected).some(m=>m.to[0]===r&&m.to[1]===c))cell.classList.add('move');const p=state[r][c];if(p){const piece=document.createElement('span');piece.className='piece '+p.player+(p.king?' king':'');cell.append(piece)}board.append(cell)}}board.onclick=e=>{const cell=e.target.closest('.cell');if(!cell)return;const r=+cell.dataset.r,c=+cell.dataset.c,p=state[r][c];if(p?.player===turn){selected=[r,c];render();return}if(selected){const action=moves(...selected).find(m=>m.to[0]===r&&m.to[1]===c);if(action){const piece=state[selected[0]][selected[1]];state[r][c]=piece;state[selected[0]][selected[1]]=null;if(action.capture)state[action.capture[0]][action.capture[1]]=null;if((piece.player==='blue'&&r===7)||(piece.player==='violet'&&r===0))piece.king=true;turn=turn==='blue'?'violet':'blue'}selected=null;render()}};document.getElementById('reset').onclick=()=>{state=fresh();turn='blue';selected=null;render()};render();
</script></body></html>`;
  return document
    .replace(".piece.blue{background:linear-gradient(145deg,#38bdf8,#1d4ed8)}", `.piece.blue{background:linear-gradient(145deg,${theme.start},${theme.end})}`)
    .replace("Vez das peças azuis", `Vez das peças ${theme.label}`)
    .replace("Azuis<strong", `${theme.title}<strong`)
    .replace("As azuis começam", `As ${theme.label} começam`)
    .replace("const board=", `const primaryLabel=${JSON.stringify(theme.label)};const board=`)
    .replace("?'azuis':'roxas'", `?primaryLabel:${JSON.stringify(theme.opponentLabel)}`)
    .replace("BUILD FORGE STUDIO · JOGO INTERATIVO", theme.medieval ? "BUILD FORGE STUDIO · REINO MEDIEVAL" : "BUILD FORGE STUDIO · JOGO INTERATIVO")
    .replace("background:radial-gradient(circle at 15% 0,#352466,#090d1c 52%,#050814)", theme.medieval ? "background:radial-gradient(circle at 15% 0,#6b3c18,#201107 52%,#090604)" : "background:radial-gradient(circle at 15% 0,#352466,#090d1c 52%,#050814)")
    .replace("border:6px solid #291c38", theme.medieval ? "border:6px solid #8c5a24" : "border:6px solid #291c38")
    .replace(".cell.light{background:#e7d7be}", theme.medieval ? ".cell.light{background:#d8bb80}" : ".cell.light{background:#e7d7be}")
    .replace(".cell.dark{background:#7c4b35}", theme.medieval ? ".cell.dark{background:#623617}" : ".cell.dark{background:#7c4b35}")
    .replace("</head>", `${medievalPresentation}${competitivePresentation}<style>.piece.violet{background:linear-gradient(145deg,${theme.opponentStart},${theme.opponentEnd})!important}.cell.light{background:${theme.boardLight}!important}.cell.dark{background:${theme.boardDark}!important}</style></head>`)
    .replace('<section class="layout">', `${competitiveMarkup}<section class="layout">`)
    .replace("</body>", `${competitiveScript}</body>`)
    .replace(`<h1>${safeName}</h1>`, theme.medieval ? `<p class="medieval-banner">♜ Coroa das Sete Torres</p><h1>${safeName}</h1>` : `<h1>${safeName}</h1>`);
}

export function createStudioPreviewDocument(preview: StudioPreview) {
  if (isCheckersProject(preview)) return createCheckersPreviewDocument(preview.project.name, detectCheckersTheme(preview));
  const index = preview.files.find((file) => file.filePath.toLowerCase() === "index.html")?.content;
  const styles = preview.files.filter((file) => /\.css$/i.test(file.filePath)).map((file) => file.content).join("\n");
  const main = preview.files.find((file) => /(?:main|app)\.(?:t|j)sx?$/i.test(file.filePath))?.content ?? "";
  const extractedBody = main.match(/innerHTML\s*=\s*`([\s\S]*?)`/)?.[1] ?? `<main><h1>${escapeHtml(preview.project.name)}</h1><p>Esta prévia será atualizada quando o Studio gerar uma tela compatível com o navegador.</p></main>`;
  return (index?.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "").replace("</head>", `<style>${styles}</style></head>`).replace(/<div\s+id=["']app["']\s*><\/div>/i, `<div id="app">${extractedBody}</div>`)) ?? `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${styles}</style></head><body>${extractedBody}</body></html>`;
}
