type StudioPreviewFile = { filePath: string; content: string; language: string };
type StudioPreview = { project: { name: string; projectType: string; framework: string }; files: StudioPreviewFile[] };

function escapeHtml(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");
}

function isCheckersProject(preview: StudioPreview) {
  return /\b(damas|checkers)\b/i.test(`${preview.project.name} ${preview.project.framework} ${preview.files.map((file) => file.content.slice(0, 300)).join(" ")}`);
}

export function createCheckersPreviewDocument(name: string) {
  const safeName = escapeHtml(name);
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeName}</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 15% 0,#352466,#090d1c 52%,#050814);color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.game{width:min(960px,100%);margin:0 auto;padding:28px 18px 44px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:22px}.eyebrow{margin:0 0 5px;color:#c4b5fd;font-size:11px;font-weight:800;letter-spacing:.16em}.top h1{margin:0;font-size:clamp(24px,4vw,38px);letter-spacing:-.04em}.status{border:1px solid rgba(167,139,250,.35);border-radius:999px;background:rgba(124,58,237,.16);padding:9px 13px;font-size:12px;font-weight:700;color:#ede9fe}.layout{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:22px}.board-wrap{border:1px solid rgba(255,255,255,.12);border-radius:26px;background:rgba(15,23,42,.72);padding:16px;box-shadow:0 24px 60px rgba(0,0,0,.3)}.board{aspect-ratio:1;display:grid;grid-template-columns:repeat(8,1fr);overflow:hidden;border-radius:14px;border:6px solid #291c38;box-shadow:0 0 0 1px rgba(255,255,255,.15)}.cell{position:relative;border:0;padding:0;cursor:pointer}.cell.light{background:#e7d7be}.cell.dark{background:#7c4b35}.cell.selected{outline:4px solid #fbbf24;outline-offset:-4px;z-index:1}.cell.move:after{content:"";position:absolute;inset:37%;border-radius:50%;background:rgba(254,240,138,.9)}.piece{position:absolute;inset:14%;border-radius:50%;border:3px solid rgba(255,255,255,.55);box-shadow:inset 0 5px 8px rgba(255,255,255,.18),inset 0 -7px 10px rgba(0,0,0,.25),0 4px 7px rgba(0,0,0,.35)}.piece.blue{background:linear-gradient(145deg,#38bdf8,#1d4ed8)}.piece.violet{background:linear-gradient(145deg,#c084fc,#6d28d9)}.piece.king:before{content:"♛";position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:clamp(14px,3vw,25px);text-shadow:0 1px 2px #111}.side{display:flex;flex-direction:column;gap:12px}.card{border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:16px;background:rgba(15,23,42,.74)}.card h2{margin:0 0 8px;font-size:15px}.card p{margin:0;color:#cbd5e1;font-size:13px;line-height:1.55}.score{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:13px}.score div{border-radius:12px;padding:10px;background:#111a31;font-size:11px;color:#94a3b8}.score strong{display:block;color:white;font-size:22px;margin-top:3px}.reset{border:0;border-radius:12px;padding:12px;background:#7c3aed;color:white;font-weight:800;cursor:pointer}.reset:hover{background:#8b5cf6}.note{margin:15px 2px 0;color:#94a3b8;font-size:12px;line-height:1.55}@media(max-width:720px){.game{padding:18px 12px 32px}.layout{grid-template-columns:1fr}.side{display:grid;grid-template-columns:1fr 1fr}.side .card:last-of-type{grid-column:span 2}.top{align-items:flex-start}.status{white-space:nowrap}}@media(max-width:400px){.side{grid-template-columns:1fr}.side .card:last-of-type{grid-column:auto}}
</style></head><body><main class="game"><header class="top"><div><p class="eyebrow">BUILD FORGE STUDIO · JOGO INTERATIVO</p><h1>${safeName}</h1></div><span id="turn" class="status">Vez das peças azuis</span></header><section class="layout"><div><div class="board-wrap"><div id="board" class="board" aria-label="Tabuleiro de damas"></div></div><p class="note">Clique em uma peça e depois em uma casa marcada. Capturas por salto também estão habilitadas nesta prévia.</p></div><aside class="side"><section class="card"><h2>Partida local</h2><p>Prévia funcional criada pelo Studio. Você pode pedir pelo chat novos modos, placar, torneios, cronômetro ou um adversário com IA.</p><div class="score"><div>Azuis<strong id="blue-score">12</strong></div><div>Roxas<strong id="violet-score">12</strong></div></div></section><section class="card"><h2>Como jogar</h2><p>As azuis começam e avançam para baixo. As roxas avançam para cima. Chegue à última linha para virar dama.</p></section><button id="reset" class="reset">Reiniciar partida</button></aside></section></main><script>
const board=document.getElementById('board'),turnNode=document.getElementById('turn'),blueScore=document.getElementById('blue-score'),violetScore=document.getElementById('violet-score');let turn='blue',selected=null;const fresh=()=>Array.from({length:8},(_,r)=>Array.from({length:8},(_,c)=>((r+c)%2? (r<3?{player:'blue',king:false}:r>4?{player:'violet',king:false}:null):null)));let state=fresh();const dirs=p=>p.king?[[-1,-1],[-1,1],[1,-1],[1,1]]:p.player==='blue'?[[1,-1],[1,1]]:[[-1,-1],[-1,1]];const inBoard=(r,c)=>r>=0&&r<8&&c>=0&&c<8;function moves(r,c){const p=state[r][c];if(!p)return[];return dirs(p).flatMap(([dr,dc])=>{const one=[r+dr,c+dc],jump=[r+2*dr,c+2*dc];const out=[];if(inBoard(...one)&&!state[one[0]][one[1]])out.push({to:one,capture:null});if(inBoard(...jump)&&state[one[0]][one[1]]?.player!==p.player&&!state[jump[0]][jump[1]])out.push({to:jump,capture:one});return out})}function render(){board.innerHTML='';let b=0,v=0;state.flat().forEach(p=>{if(p?.player==='blue')b++;if(p?.player==='violet')v++});blueScore.textContent=b;violetScore.textContent=v;turnNode.textContent='Vez das peças '+(turn==='blue'?'azuis':'roxas');for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.className='cell '+((r+c)%2?'dark':'light');cell.dataset.r=r;cell.dataset.c=c;if(selected&&selected[0]===r&&selected[1]===c)cell.classList.add('selected');if(selected&&moves(...selected).some(m=>m.to[0]===r&&m.to[1]===c))cell.classList.add('move');const p=state[r][c];if(p){const piece=document.createElement('span');piece.className='piece '+p.player+(p.king?' king':'');cell.append(piece)}board.append(cell)}}board.onclick=e=>{const cell=e.target.closest('.cell');if(!cell)return;const r=+cell.dataset.r,c=+cell.dataset.c,p=state[r][c];if(p?.player===turn){selected=[r,c];render();return}if(selected){const action=moves(...selected).find(m=>m.to[0]===r&&m.to[1]===c);if(action){const piece=state[selected[0]][selected[1]];state[r][c]=piece;state[selected[0]][selected[1]]=null;if(action.capture)state[action.capture[0]][action.capture[1]]=null;if((piece.player==='blue'&&r===7)||(piece.player==='violet'&&r===0))piece.king=true;turn=turn==='blue'?'violet':'blue'}selected=null;render()}};document.getElementById('reset').onclick=()=>{state=fresh();turn='blue';selected=null;render()};render();
</script></body></html>`;
}

export function createStudioPreviewDocument(preview: StudioPreview) {
  if (isCheckersProject(preview)) return createCheckersPreviewDocument(preview.project.name);
  const index = preview.files.find((file) => file.filePath.toLowerCase() === "index.html")?.content;
  const styles = preview.files.filter((file) => /\.css$/i.test(file.filePath)).map((file) => file.content).join("\n");
  const main = preview.files.find((file) => /(?:main|app)\.(?:t|j)sx?$/i.test(file.filePath))?.content ?? "";
  const extractedBody = main.match(/innerHTML\s*=\s*`([\s\S]*?)`/)?.[1] ?? `<main><h1>${escapeHtml(preview.project.name)}</h1><p>Esta prévia será atualizada quando o Studio gerar uma tela compatível com o navegador.</p></main>`;
  return (index?.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "").replace("</head>", `<style>${styles}</style></head>`).replace(/<div\s+id=["']app["']\s*><\/div>/i, `<div id="app">${extractedBody}</div>`)) ?? `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${styles}</style></head><body>${extractedBody}</body></html>`;
}
